[tool.black]
line-length = 90
include = '.*src\/.*\.pyi?$'
exclude = '''
    /(
        .*urls\.py
        | \.git
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | dist
         # The following are specific to Black, you probably don't want those.
        | blib2to3
        | tests/data
         # Project Directories
        | __pycache__
        | migrations
        | static
        | templates
    )/
'''
