# Generated by Django 2.0.5 on 2018-05-23 15:42

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casting_time', models.CharField(blank=True, max_length=128, null=True)),
                ('classes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=24), size=24)),
                ('components', django.contrib.postgres.fields.jsonb.JSONField()),
                ('description', models.CharField(blank=True, max_length=10240, null=True)),
                ('higher_levels', models.CharField(blank=True, max_length=1024, null=True)),
                ('duration', models.CharField(blank=True, max_length=128, null=True)),
                ('level', models.SmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('spell_range', models.CharField(blank=True, max_length=128, null=True)),
                ('ritual', models.BooleanField(default=False)),
                ('school', models.CharField(blank=True, max_length=128, null=True)),
                ('spell_type', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
