# Generated by Django 2.0.5 on 2018-05-23 19:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spellbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generic Spellbook', max_length=64)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('classes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=24), size=24)),
            ],
        ),
        migrations.AlterModelOptions(
            name='spell',
            options={'ordering': ['id']},
        ),
    ]
