# Generated by Django 2.0.5 on 2018-05-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0003_spellbook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellbook',
            name='spells',
            field=models.ManyToManyField(to='spells.Spell'),
        ),
    ]
